### ISSUE TITLE
A screen for the basic Calculator

### ISSUE THREAD

**Issue by smilewithkhushi** [smilewithkhushi/BasicNative#1]
src/screens/calculator/calculator.js

**Comment by VanshikaSabharwal** [comment]
i can do it. i am a GSSOC contributor .kindly assign this issue to me

**Comment by Pratyaksh0910** [comment]
Hey there! I'm Pratyaksh Agrawal, a full-stack MERN web developer. With experience in numerous successful MERN stack projects, I excel in HTML, CSS,JavaScript,C, C++,jQuery, Node.js, React.js, Bootstrap, Tailwind, Express, MongoDB, API,GraphQL,WebRTC.
You can find me on LinkedIn : https://www.linkedin.com/in/pratyaksh-agrawal-2aa032220/
Looking forward to contributing to GSSOC 2024!
