### ISSUE TITLE
[ADD] A QR Code Scanner

### ISSUE THREAD

**Issue by smilewithkhushi** [smilewithkhushi/BasicNative#10]
Add a dedicated screen to a QR code scanner which re-directs to an external URL on scanning the QR.

Directory: /src/screens/QRScanner

**Comment by VanshikaSabharwal** [comment]
i am a GSSOC contributor .please assign this to me

**Comment by GOKULGSECE** [comment]
I have done a QR Generator in React So i have an better experience to develop an qr code dynamically i want to explore React-Native so assign this issue to me

**Comment by smilewithkhushi** [comment]
@Hemu21 is assigned to work on the following issue. Make sure you raise the associated PR within 2-3 Days.
Feel free to reach out if you have any queries/doubts.
Happy contributing!😊

**Comment by Hemu21** [comment]
@smilewithkhushi I had Created the PR. can you please check it.

**Comment by Hemu21** [comment]
@smilewithkhushi can you please merge my PR.
