### ISSUE TITLE
💡[Feature]: Adding To Do list project for beginners

### ISSUE THREAD

**Issue by BhaktiMore18** [smilewithkhushi/BasicNative#108]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature Description

The To-Do List App is a simple project that allows users to create, update, and delete tasks, helping them stay organized. It features a clean user interface styled with Tailwind CSS, making it easy to use and visually appealing.

### Use Case

Add Task: Users can create new tasks by entering a title.
View Tasks: Users can see a list of all their tasks.
Delete Task: Users can remove tasks they no longer need.
Mark as Completed: Users can mark tasks as done.

### Priority

High

### Record

- [x] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by BhaktiMore18** [comment]
@akjain1509 can you assign this issue to me, I'd love to work on this!

**Comment by smilewithkhushi** [comment]
A to-do list has already been added to the project! It would be great if you can look into some feature enhancements or other additions.
