### ISSUE TITLE
[IMPROVEMENT] Enhance the UI of the home screen

### ISSUE THREAD

**Issue by smilewithkhushi** [smilewithkhushi/BasicNative#11]
Enhance the UI of the home screen of the application. This can be done by the following : 

- Introducing the new color theme for the home page
- Enhancing the layout of the buttons
- Adding effects of the buttons
- Improving the background

File Directory: /src/screens/Home/home.js

**Comment by VanshikaSabharwal** [comment]
i am a GSSOC contributor . i am willing to improve UI .please assign this issue to me.

**Comment by PoojaGadagi08** [comment]
Hello @smilewithkhushi  mam
I would like to work on this issue as a contributor to the GSSOC. please assign this to me!
I have relevant skills that definitely help to enhance the website.

**Comment by MuhammadUmarMalik** [comment]
Hello @smilewithkhushi Mam,
I would like to work on this issue as a contributor to the GSSOC'24. Kindly assign this issue to me. I have relevant skills that help to enhance the app.

**Comment by akjain1509** [comment]
Hello @smilewithkhushi Mam,
I'm eager to enhance the UI for this task and add animation effects as well, contributing to GSSOC. Could you kindly assign this to me?

**Comment by Manaswini123456** [comment]
I would like to contribute, I am a GSSOC'24 contributor. Kindly, assign me with this issue.

**Comment by smilewithkhushi** [comment]
@VanshikaSabharwal  is assigned to work on the following issue. Make sure you raise the associated PR within 2-3 Days.
Feel free to reach out if you have any queries/doubts.
Happy contributing!😊

**Comment by VanshikaSabharwal** [comment]
Hey @smilewithkhushi , I have added styling to the home screen. i am sharing a screenshot of the UI . I have kept it simple yet eye relaxing.
![Uploading Screenshot 2024-05-12 112919.png…]()

**Comment by VanshikaSabharwal** [comment]
Hey @smilewithkhushi , I have added styling to the home screen. i am sharing a screenshot of the UI . I have kept it simple yet eye relaxing.

![Screenshot 2024-05-12 112919](https://github.com/smilewithkhushi/BasicNative/assets/143436704/64816962-aeca-416f-84e8-c664271776e4)

**Comment by VanshikaSabharwal** [comment]
@smilewithkhushi I am raising PR .so, you can merge it. to the project.
