### ISSUE TITLE
[ADD] A Coding Quiz Game

### ISSUE THREAD

**Issue by smilewithkhushi** [smilewithkhushi/BasicNative#13]
This issue aims to work on creating a dedicated screen for a Coding Quiz game, and involves working on the following : 

- Creating a Quiz Game, with multiple choice questions.
- The quiz can have upto 10 questions.
- You can either integrate any external APIs or the Json files for the quiz questions.
- Assign the scores on the basis of correct answers as well. +1 mark for every correct question.
- {BONUS} Adding a timer would be a plus point!

Screen Directory: /src/screens/CodingQuiz

**Comment by PoojaGadagi08** [comment]
Hello @smilewithkhushi  mam
I would like to work on this issue as a contributor to the GSSOC. please assign this to me!
I have relevant skills that definitely help to enhance the website.

**Comment by MuhammadUmarMalik** [comment]
Hello @smilewithkhushi Mam,
I would like to work on this issue as a contributor to the GSSOC'24. Kindly assign this issue to me. I have relevant skills that help to enhance the app.

**Comment by akjain1509** [comment]
Hello @smilewithkhushi Mam,
I'm highly interested in tackling the Coding Quiz game contribution for GSSOC. I'm confident in delivering a polished screen in /src/screens/CodingQuiz, including a timer (bonus!). 
Kindly assign this to me

**Comment by smilewithkhushi** [comment]
@MuhammadUmarMalik  is assigned to work on the issue. Make sure you raise the associated PR within 2-3 Days.
Feel free to reach out if you have any queries/doubts.
Happy contributing!😊

**Comment by smilewithkhushi** [comment]
@MuhammadUmarMalik have you started working on the issue? or should i assign this issue to someone else who is willing to contribute!

**Comment by saikrishna823** [comment]
@smilewithkhushi ,I would like to work on this issue.Kindly assign issue to me.I am participant of GSSOC'24.Will send PR in 2-3 days

**Comment by MaryamMohamedYahya** [comment]
I would like to make this quiz. Kindly assign this to me under Gssoc'2024

**Comment by Hemu21** [comment]
@smilewithkhushi can you please assign this to me.

**Comment by lassmara** [comment]
please assign me this issue

**Comment by Tanishka023** [comment]
Hey @smilewithkhushi I am excited to contribute to this, and I can do this easily. Please assign this to GSSOC'24.

**Comment by Manaswini123456** [comment]
@smilewithkhushi Please assign me with this issue.

**Comment by Sowham-3098** [comment]
@smilewithkhushi please assign this to me

**Comment by Manaswini123456** [comment]
@smilewithkhushi I would like to work upon this issue. Kindly assign this to me

**Comment by smilewithkhushi** [comment]
@Manaswini123456 raise the PR in 2-3 days.

**Comment by Manaswini123456** [comment]
@smilewithkhushi Will do the needful, and generate the PR within 3 days.
