### ISSUE TITLE
[ADD] To-Do List App

### ISSUE THREAD

**Issue by smilewithkhushi** [smilewithkhushi/BasicNative#15]
This issue involves working on the addition of a To-Do list application screen in the app. The details are as follows : 

1. Screen 1 (Main Screen):
Display a list of tasks with checkboxes to mark them as completed.
Button to add a new task.

2. Screen 2 (Add Task):
Input field to add a new task.
Button to save the task.

Directory: /src/screens/ToDoList

**Comment by Hemu21** [comment]
@smilewithkhushi  can you please assign it to me.

**Comment by ask2901** [comment]
Hello @smilewithkhushi mam. I would like to work on this feature. Kindly assign me this task.

**Comment by akjain1509** [comment]
Hello @smilewithkhushi mam, I'm keen on implementing the To-Do list feature. Please assign me this task. I'll create screens for displaying tasks and adding new ones. Directory: /src/screens/ToDoList.

**Comment by Manaswini123456** [comment]
I have build a similar product in the past with the required tech stack, therefore have a good amount of knowledge regarding the same, Kindly, assign me the issue.

**Comment by smilewithkhushi** [comment]
@akjain1509   is assigned to work on the issue. Make sure you raise the associated PR within 2-3 Days.
Feel free to reach out if you have any queries/doubts.
Happy contributing!😊
