### ISSUE TITLE
[ADD] an Expense Tracker Screen

### ISSUE THREAD

**Issue by smilewithkhushi** [smilewithkhushi/BasicNative#16]
This issue involves working on creating an expense tracker screen on the app. The following are the details : 

1. Screen 1 (Dashboard):
Display total expenses and income for the current month.
Chart showing expense distribution by category.

2. Screen 2 (Add Expense):
Form to add a new expense with fields for amount, category, and date.

You can make changes in the UI or the workflow accordingly, but it should fulfill the goal of this issue.

Directory: /src/screens/ExpenseTracker

**Comment by ask2901** [comment]
Hello @smilewithkhushi mam. I would like to work on this feature. Kindly assign it to me.

**Comment by akjain1509** [comment]
Hello @smilewithkhushi Mam,
I'm highly interested in tackling the Expense Tracker contribution for GSSOC. I'm confident in delivering a polished screen in /src/screens/ExpenseTracker.
Kindly assign this to me.

**Comment by smilewithkhushi** [comment]
@ask2901 is assigned to work on the issue. Make sure you raise the associated PR within 2-3 Days.
Feel free to reach out if you have any queries/doubts.
Happy contributing!😊

**Comment by saikrishna823** [comment]
Hey @smilewithkhushi please assign this issue to me.I.will send PR within 2-3 days.

**Comment by akjain1509** [comment]
Hello @smilewithkhushi Mam,
I'm highly interested in tackling the Expense Tracker contribution for GSSOC. I'm confident in delivering a polished screen in /src/screens/ExpenseTracker.
Kindly assign this to me.

**Comment by smilewithkhushi** [comment]
@akjain1509 submit the PR within 2-3 days.
