### ISSUE TITLE
[ADD] a Fitness Tracker

### ISSUE THREAD

**Issue by smilewithkhushi** [smilewithkhushi/BasicNative#17]
This issue involves adding a  few dedicated screens for a Fitness Tracker, which is as follows : 

1. Screen 1 (Workout Overview):
Display a list of past workouts with details like duration, calories burned, etc.
Option to add a new workout.
2. Screen 2 (Add Workout):
Select from predefined workout types or add a custom workout.
Input fields for duration, calories burned, etc.

You can make changes in the workflow or UI accordingly, but the code should fulfill all the given functionalities in the application.

Directory: /src/screens/FitnessTracker

**Comment by Hemu21** [comment]
@smilewithkhushi  can you please assign this to me. I want to contribute to it.

**Comment by muskandn** [comment]
Hello @smilewithkhushi 
I want to contribute to this issue under GSSoC'24.
Please consider me assigning it to me.

**Comment by akjain1509** [comment]
Hello @smilewithkhushi Mam,
I'm eager to contributing to this task under GSSOC. Could you kindly assign this to me?

**Comment by smilewithkhushi** [comment]
@muskandn is assigned to work on the issue. Make sure you raise the associated PR within 2-3 Days.
Feel free to reach out if you have any queries/doubts.
Happy contributing!😊

**Comment by smilewithkhushi** [comment]
@Manaswini123456 I have added some new issues which you might like! Please have a look and let me know if you'd like to contribute to them. Would love to assign those issues to you.

**Comment by Manaswini123456** [comment]
Thank you so much for connecting. Will take a look at them and let you know @smilewithkhushi

**Comment by muskandn** [comment]
> @muskandn is assigned to work on the issue. Make sure you raise the associated PR within 2-3 Days. Feel free to reach out if you have any queries/doubts. Happy contributing!😊

Thank you @smilewithkhushi  for assigning this issue to me. I will start working on it asap.

**Comment by muskandn** [comment]
as @Manaswini123456 said I am also facing the same issue
![image](https://github.com/smilewithkhushi/BasicNative/assets/99585352/a408b1f7-8ee7-4e1f-8603-0cd05d15d654)

Please suggest what to do @smilewithkhushi

**Comment by muskandn** [comment]
Regrettably, I must withdraw from the assigned issue due to unforeseen circumstances. Kindly reassign this task to another contributor. I look forward to continuing my support for the project in other capacities.

**Comment by Hemu21** [comment]
> @smilewithkhushi can you please assign this to me. I want to contribute to it.

@smilewithkhushi can you please assign this to me.

**Comment by Manaswini123456** [comment]
@smilewithkhushi Can you please assign me with this issue.

**Comment by smilewithkhushi** [comment]
@Manaswini123456 assigned! pls submit a PR in 3-4 days. all the best

**Comment by Manaswini123456** [comment]
@smilewithkhushi Thank you so much will start working upon the issue.

**Comment by Manaswini123456** [comment]
@smilewithkhushi I have generated the PR, could you please look into it, and suggest changes if required.
