### ISSUE TITLE
[IMPROVEMENT] ReadMe.md

### ISSUE THREAD

**Issue by smilewithkhushi** [smilewithkhushi/BasicNative#18]
This issue involves implementing the updates on the readme. The new ReadMe must contain the following : 

- the preview of all the screens and the mini projects which have been added in the application.
- Detailed description of the headings of the existing ReadMe.
- Any methods/practices to enhance the readability of the current ReadMe.

You can also suggest changes  from your end.
(This issue will be assigned after the addition of 4-5 mini projects/screens in the application)

**Comment by nawarajshah** [comment]
@smilewithkhushi  can you assign this issue to me?

**Comment by Manaswini123456** [comment]
please assign the above mentioned issue to me

**Comment by smilewithkhushi** [comment]
@nawarajshah is assigned to work on the issue. Make sure you raise the associated PR within 3-5 Days after updating the screens with the latest project preview.
Feel free to reach out if you have any queries/doubts.
Happy contributing!😊

**Comment by Manaswini123456** [comment]
@smilewithkhushi Please assign me with this issue

**Comment by Manaswini123456** [comment]
I would like to add my insights to it

**Comment by smilewithkhushi** [comment]
@Manaswini123456 assigned! please raise the PR within 2-3 days.

**Comment by Manaswini123456** [comment]
@smilewithkhushi thank you for assigning. Will look into it.

**Comment by Manaswini123456** [comment]
I'll generate the PR by tonight
