### ISSUE TITLE
[ADD] a Recipe finder App

### ISSUE THREAD

**Issue by smilewithkhushi** [smilewithkhushi/BasicNative#19]
This issue involves working on the Recipe Finder App. The following are the features and details : 

- Allow users to search for recipes by name or ingredients.
- Display recipe details including ingredients and instructions.
- Save favorite recipes for later viewing.
- Integrate with a recipe API like Spoonacular.
You can make changes in the workflow or the UI accordingly, but make sure to implement all these features.

Directory: /src/screens/RecipeFinder

**Comment by Hemu21** [comment]
@smilewithkhushi I want to work on it. Can you please assign this to me.

**Comment by muskandn** [comment]
Hello @smilewithkhushi 
I want to contribute to this issue under GSSoC'24.
Please consider me assigning it to me.

**Comment by richab246** [comment]
Hey @smilewithkhushi , I would love to contribute to this issue, please assign it to me under GSSoC'24

**Comment by smilewithkhushi** [comment]
@richab246 is assigned to work on the issue. Make sure you raise the associated PR within 2-3 Days.
Feel free to reach out if you have any queries/doubts.
Happy contributing!😊

**Comment by saikrishna823** [comment]
Hey @smilewithkhushi ,I would like to contribute to this issue.I will complete within 2-3 days

**Comment by smilewithkhushi** [comment]
@saikrishna823 assigned you the issue. please raise the pr within given days.

**Comment by richab246** [comment]
Hey @smilewithkhushi, can you give me just one day, I have almost completed it, my final exams were going that's why I couldn't complete it on time

**Comment by saikrishna823** [comment]
hey @smilewithkhushi ,completed application.I have sent a PR request too.Kindly check it and let me know any issues.

**Comment by saikrishna823** [comment]
@smilewithkhushi ,could you rename the Level 3 to level3? Because of wrong labelling points are not added to leaderboard.Please do it.

**Comment by saikrishna823** [comment]
It should be lowercase without any spaces.Please do it.
