### ISSUE TITLE
Dropdown text in the home screen

### ISSUE THREAD

**Issue by smilewithkhushi** [smilewithkhushi/BasicNative#2]
A dropdown text feature on click which gives a 1-liner info about a particular button (having the daywise progress made in the app)

**Comment by VanshikaSabharwal** [comment]
i can do it .i am a GSSOC contributor .please assign this to me.

**Comment by MuhammadUmarMalik** [comment]
Hello @smilewithkhushi Mam,
I would like to work on this issue as a contributor to the GSSOC'24. Kindly assign this issue to me. I have relevant skills that help to enhance the app.
