### ISSUE TITLE
[IMPROVEMENT] Learn.md

### ISSUE THREAD

**Issue by smilewithkhushi** [smilewithkhushi/BasicNative#21]
- Learn repos should have a LEARN.md file to teach student how to build your project step by step. You can explain how to build this project with text, code snippets, images, or even short (5 minute) long video lessons. 

- The LEARN.md file requires you to think critically about how to explain the building of this project and how to also make it engaging. 

- This issue would like you to reflect on how difficult it was to get to your level of knowledge, and then provide friendly guidance to help other contributors to learn.

- Reference: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/Learn.md

**Comment by adrikaDwivedi** [comment]
hi @smilewithkhushi  , i would like to improve the LEARN.md for each repo , kindly assign the part to me

**Comment by smilewithkhushi** [comment]
@adrikaDwivedi assigned you the issue! you've 2-3 days to submit a PR.
All the best!!

**Comment by Manaswini123456** [comment]
@smilewithkhushi Can you please assign this to me. Would love to contribute

**Comment by smilewithkhushi** [comment]
@Manaswini123456 assigned you the issue! please submit the PR by sunday. try to make it in the best ways you can. 
all the best!
