### ISSUE TITLE
[ADD] a random color generator screen

### ISSUE THREAD

**Issue by smilewithkhushi** [smilewithkhushi/BasicNative#22]
This issue involves working on adding a screen which has the following features : 

1- An interactive UI screen.
2- A Button which generate the hex color code randomly and shows the colour in the preview on any box/element,

Feel free to add any other features on this screen.

Directory: /src/screens/HexColorGenerator

**Comment by Manaswini123456** [comment]
@smilewithkhushi please assign me with this issue

**Comment by adrikaDwivedi** [comment]
hi @smilewithkhushi  , i am interested in working on this issue. Kindly assign this to me.

**Comment by smilewithkhushi** [comment]
@Manaswini123456 assigned you the issue! you've 2-3 days to submit the PR. All the best!

**Comment by Manaswini123456** [comment]
@smilewithkhushi thanks, will do the needful
