### ISSUE TITLE
[ADD] a QR Code Generator

### ISSUE THREAD

**Issue by smilewithkhushi** [smilewithkhushi/BasicNative#23]
This issue involves the addition of a dedicated screen for a QR code generator and implementing the following features : 
- An input field where the user can add the URL.
- A valid URL checker implemented,
- A button which generates the QR code on click.
- The preview of the QR code via a modal or another screen.
- Easy to navigate UI which matches the minimal theme of the application

Feel free to make changes in the workflow but you must implement all the functionalities.

Directory: /src/screens/QRGenerator

**Comment by muskandn** [comment]
Hello @smilewithkhushi
I want to contribute to this issue under GSSoC'24.
Please consider me assigning it to me.

**Comment by Hemu21** [comment]
@smilewithkhushi can you please assign this issue to me.

**Comment by akjain1509** [comment]
HI @smilewithkhushi ,
Please assign this task to me . i will definitely do it. I have completed to do list app too.
Hope you will assign me this task

**Comment by smilewithkhushi** [comment]
@Hemu21 assigned you this issue! You've 2-3 days to submit the PR. all the best!

**Comment by Hemu21** [comment]
@smilewithkhushi Thank you for assigning me.
