### ISSUE TITLE
[ADD] a Movie Finder App Screen

### ISSUE THREAD

**Issue by smilewithkhushi** [smilewithkhushi/BasicNative#24]
This issue involves the addition of a screen where you can search and find your favourite movies. The following features have to be implemented : 
- A screen which finds the movie based on user search.
- A new screen or a modal to display the info about the movie (cast, plot, theme , etc).
- Poster of the movies
- Recommended movies based on user search (optional)

Feel free to add the features of your choice and modify the UI and workflow accordingly!

Directory: src/screens/MovieFinder

**Comment by Manaswini123456** [comment]
@smilewithkhushi  please assign me with this issue. I would like to contribute and provide my insights and solutions. Would love to connect.

**Comment by smilewithkhushi** [comment]
@Manaswini123456 is assigned to work on the issue. Make sure you raise the associated PR within 2-3 Days.
Feel free to reach out if you have any queries/doubts.
Happy contributing!😊

**Comment by Manaswini123456** [comment]
Thank you so much. Will start working on it and give you the update regarding the same

**Comment by Manaswini123456** [comment]
@smilewithkhushi 
![image](https://github.com/smilewithkhushi/BasicNative/assets/91537487/460ec10b-315d-4432-a47d-53bac0cfa0c2)
there is an issue when I am trying to 'npm install'. If you could provide a path for the same

**Comment by Manaswini123456** [comment]
@smilewithkhushi Hello, the given issue has been solved and the screenshots are as follows:
1. 
![WhatsApp Image 2024-05-12 at 18 32 20_cbf47f1d](https://github.com/smilewithkhushi/BasicNative/assets/91537487/cb0b9afb-bbca-4467-8a86-faded5dd714e)

2. 
![WhatsApp Image 2024-05-12 at 18 32 02_2ca6a729](https://github.com/smilewithkhushi/BasicNative/assets/91537487/cddeb099-025f-4229-8615-0ece976f5617)

Kindly check and let me know. In this the optional part hasn't been added. Let me know whether these are fine or not. And thank you for the opportunity.

**Comment by Manaswini123456** [comment]
@smilewithkhushi I have raised the PR kindly check and merge
