### ISSUE TITLE
💡[FEATURE]: Anime Finder

### ISSUE THREAD

**Issue by Sypher0Dronzer** [smilewithkhushi/BasicNative#60]
**Is your feature request related to a problem? Please describe.**
It targets audience who watch anime 

**Describe the solution you'd like**
the user can search the anime name and get the details of that anime

**Describe alternatives you've considered**

**Additional context**

@smilewithkhushi  please assign me this issue under label gssoc24

**Comment by smilewithkhushi** [comment]
interesting. you can work on this issue! submit the PR in 2-3 days
