### ISSUE TITLE
💡[FEATURE]: Pokedex - To get pokemon details

### ISSUE THREAD

**Issue by Sypher0Dronzer** [smilewithkhushi/BasicNative#61]
**Is your feature request related to a problem? Please describe.**
No just a fun app for pokemon fans

**Describe the solution you'd like**
I wish to add a feature where on searching for a pokemon you get the details of it

![image](https://github.com/smilewithkhushi/BasicNative/assets/83546205/e18c51cb-c514-4f5e-98fe-b6649fc3d101)

**Describe alternatives you've considered**

**Additional context**

please assign me this issue @smilewithkhushi  under gssoc

**Comment by smilewithkhushi** [comment]
assigned! submit the PR in 3-4 days.
keep the UI as interactive as possible and focus on enhancing user experience in the issues assigned to you :)
all the best
