### ISSUE TITLE
💡[Feature]:  Timer-App

### ISSUE THREAD

**Issue by Varshi45** [smilewithkhushi/BasicNative#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

A Timer app that has following funtionalities

- timer
- different time options (hours/minutes/seconds)
- stopwatch
- laps 

### Use Case

User can use Stopwatch/Timer using the app to keep track of the time

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by smilewithkhushi** [comment]
assigned! you have 2-3 days to submit the PR. also, focus on interactive UI and enhancing user's experience.
